apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-sts
spec:
  selector:
    matchLabels:
      app: es
  serviceName: es-headless-svc
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: es
    spec:
      nodeName: leidong     #指定节点名称
      containers:
      - name: es
        image: elasticsearch:7.16.2
        ports:
          - containerPort: 9200
            name: rest
            protocol: TCP
          - name: inter-node
            containerPort: 9300
            protocol: TCP
        env:
          - name: node.name
            value: "es-master"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: ELASTIC_PASSWORD
            value: "Mjolnir"
          - name: node.max_local_storage_nodes
            value: "3"
          - name: xpack.security.enabled
            value: "true"
          - name: discovery.seed_hosts
            value: "192.168.1.230"
            # value: "192.168.1.230,192.168.1.231,192.168.1.232"
          - name: cluster.initial_master_nodes
            value: "es-master"
          - name: xpack.security.transport.ssl.enabled
            value: "true"
        volumeMounts:
        - name: es-config-vol
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: es-config-vol
        configMap:  # kubectl create configmap es-config --from-file=elasticsearch.yml
          name: es-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml